INSERT INTO User (UserID, Login, Password, RoomsCreated, RoomsUsed)
VALUES (0, "Banana", "qwerty", "ROOM1\n", "ROOM1\nROOM2\n")
INSERT INTO User (UserID, Login, Password, RoomsCreated, RoomsUsed)
VALUES (1, "Patata", "uiopa", "ROOM3\n", "ROOM3\nROOM2\n")
INSERT INTO User (UserID, Login, Password, RoomsCreated, RoomsUsed)
VALUES (2, "Pomodo", "sdfgh", "ROOM2\n", "ROOM4\nROOM2\nROOM1\n")
INSERT INTO User (UserID, Login, Password, RoomsCreated, RoomsUsed)
VALUES (3, "Carota", "jklzx", "ROOM5\n", "ROOM5\nROOM3\n")
INSERT INTO User (UserID, Login, Password, RoomsCreated, RoomsUsed)
VALUES (4, "Brocco", "cvbnm", "ROOM4\n", "ROOM1\nROOM4\n")

INSERT INTO Chatroom (RoomID, Name, Owner, Messages)
VALUES (100, "ROOM1", "Banana", "caio\n")
INSERT INTO Chatroom (RoomID, Name, Owner, Messages)
VALUES (101, "ROOM2", "Pomodo", "bella\n")
INSERT INTO Chatroom (RoomID, Name, Owner, Messages)
VALUES (102, "ROOM3", "Patata", "hola\n")
INSERT INTO Chatroom (RoomID, Name, Owner, Messages)
VALUES (103, "ROOM4", "Brocco", "dasvidania\n")
INSERT INTO Chatroom (RoomID, Name, Owner, Messages)
VALUES (104, "ROOM5", "Carota", "gut\n")

INSERT INTO Message (MessageID, Author, Room, Content, Date)
VALUES (10000, "Banana", "ROOM1", "caio\n")
INSERT INTO Message (MessageID, Author, Room, Content, Date)
VALUES (10001, "Pomodo", "ROOM2", "bella\n")
INSERT INTO Message (MessageID, Author, Room, Content, Date)
VALUES (10002, "Patata", "ROOM3", "hola\n")
INSERT INTO Message (MessageID, Author, Room, Content, Date)
VALUES (10003, "Brocco", "ROOM4", "dasvidania\n")
INSERT INTO Message (MessageID, Author, Room, Content, Date)
VALUES (10004, "Carota", "ROOM5", "gut\n")
